extrn mapperinit00:near
extrn mapperinit01:near
extrn mapperinit02:near
extrn mapperinit03:near
extrn mapperinit04:near
extrn mapperinit07:near
extrn mapperinit09:near
extrn mapperinit11:near
extrn mapperinit15:near
extrn mapperinit16:near
extrn mapperinit17:near
extrn mapperinit34:near
extrn mapperinit64:near
extrn mapperinit68:near
extrn mapperinit71:near
extrn mapperinit76:near
extrn mapperinit99:near
extrn mapperinit151:near
extrn mapperinit232:near
extrn mapperinit666:near


extrn bglatch:near
extrn sprite8latch:near
extrn sprite16latch:near
